# Generated by Django 3.2.3 on 2021-05-19 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('type', models.CharField(choices=[('string', 'string'), ('boolean', 'boolean')], default='string', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.CreateModel(
            name='BooleanValue',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task.variable')),
                ('Value', models.BooleanField(default=False)),
            ],
            bases=('task.variable',),
        ),
    ]
